spring.application.name=investments-api

# Chave secreta usada para assinar o token JWT
jwt.secret=senha-secreta-longa-nao-funciona-nunca

# Tempo de expiração do token (opcional, mas útil)
jwt.expiration=3600000

spring.datasource.url=jdbc:h2:file:./data/investmentsdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Configurações JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.security.user.name=admin
spring.security.user.password=admin